// src/utils/formMappings.js

export const formMappings = {
  student: {
    collectionName: 'students',
    primaryKey: 'id',
    label: 'Student',
    recordType: 'student',
    initialData: (defaults = {}) => ({
      id: '',
      studentIdCard: '',
      firstName: '',
      lastName: '',
      email: '',
      username: '',
      phone: '',
      password: '',
      confirmPassword: '',
      courseCodes: [],
      eventCodes: [],
      ...defaults,
    }),
  },
  studentEvent: {
    collectionName: 'studentEvents',
    primaryKey: 'eventCode',
    label: 'Personal Event',
    recordType: 'studentEvent',
    initialData: (defaults = {}) => ({
      eventCode: '',
      eventName: '',
      notes: '',
      startDate: new Date().toISOString().slice(0, 10),
      endDate: new Date().toISOString().slice(0, 10),
      allDay: false,
      startHour: '09:00',
      endHour: '10:00',
      ...defaults,
    }),
  },
  year: {
    collectionName: 'years',
    primaryKey: 'yearCode',
    label: 'Year',
    recordType: 'year',
    initialData: (defaults = {}) => ({
      yearCode: `YEAR-${Date.now()}`,
      yearNumber: new Date().getFullYear().toString(),
      startDate: '',
      endDate: '',
      semesters: [],
      ...defaults,
    }),
  },
  semester: {
    collectionName: 'years',
    primaryKey: 'semesterCode',
    label: 'Semester',
    recordType: 'semester',
    initialData: (defaults = {}) => ({
      semesterCode: `SEM-${Date.now()}`,
      yearCode: '',
      semesterNumber: '',
      startDate: '',
      endDate: '',
      ...defaults,
    }),
  },
  course: {
    collectionName: 'courses',
    primaryKey: 'courseCode',
    label: 'Course',
    recordType: 'course',
    initialData: (defaults = {}) => ({
      courseCode: `C-${Date.now()}`,
      courseName: '',
      semesterCode: '',
      lecturerId: '',
      roomCode: '',
      hours: [{ day: '', start: '09:00', end: '12:00' }],
      notes: '',
      zoomMeetinglink: '',
      ...defaults,
    }),
  },
  courseMeeting: {
    collectionName: 'coursesMeetings',
    primaryKey: 'id',
    label: 'Course Meeting',
    recordType: 'courseMeeting',
    initialData: (defaults = {}) => ({
      id: `CM-${Date.now()}`,
      title: '',
      start: new Date().toISOString(),
      end: new Date().toISOString(),
      lecturerId: '',
      roomCode: '',
      courseCode: '',
      semesterCode: '',
      notes: '',
      zoomMeetinglink: '',
      type: 'courseMeeting',
      allDay: false,
      ...defaults,
    }),
  },
  lecturer: {
    collectionName: 'lecturers',
    primaryKey: 'id',
    label: 'Lecturer',
    recordType: 'lecturer',
    initialData: (defaults = {}) => ({
      id: `L-${Date.now()}`,
      name: '',
      email: '',
      phone: '',
      ...defaults,
    }),
  },
  site: {
    collectionName: 'sites',
    primaryKey: 'siteCode',
    label: 'Site',
    recordType: 'site',
    initialData: (defaults = {}) => ({
      siteCode: `SITE-${Date.now()}`,
      siteName: '',
      notes: '',
      rooms: [],
      ...defaults,
    }),
  },
  room: {
    collectionName: 'sites',
    primaryKey: 'roomCode',
    label: 'Room',
    recordType: 'room',
    initialData: (defaults = {}) => ({
      roomCode: `ROOM-${Date.now()}`,
      siteCode: '',
      roomName: '',
      notes: '',
      ...defaults,
    }),
  },
  holiday: {
    collectionName: 'holidays',
    primaryKey: 'holidayCode',
    label: 'Holiday',
    recordType: 'holiday',
    initialData: (defaults = {}) => ({
      holidayCode: `HOL-${Date.now()}`,
      holidayName: '',
      startDate: new Date().toISOString().slice(0, 10),
      endDate: new Date().toISOString().slice(0, 10),
      notes: '',
      type: 'holiday',
      allDay: true, // Holidays default to all-day
      ...defaults,
    }),
  },
  vacation: {
    collectionName: 'vacations',
    primaryKey: 'vacationCode',
    label: 'Vacation',
    recordType: 'vacation',
    initialData: (defaults = {}) => ({
      vacationCode: `VAC-${Date.now()}`,
      vacationName: '',
      startDate: new Date().toISOString().slice(0, 10),
      endDate: new Date().toISOString().slice(0, 10),
      notes: '',
      type: 'vacation',
      allDay: true, // Vacations default to all-day
      ...defaults,
    }),
  },
  event: {
    collectionName: 'events',
    primaryKey: 'eventCode',
    label: 'General Event',
    recordType: 'event',
    initialData: (defaults = {}) => ({
      eventCode: `EVT-${Date.now()}`,
      eventName: '',
      startDate: new Date().toISOString().slice(0, 10),
      endDate: new Date().toISOString().slice(0, 10),
      allDay: false,
      startHour: '09:00',
      endHour: '10:00',
      notes: '',
      type: 'event',
      ...defaults,
    }),
  },
  task: {
    collectionName: 'tasks',
    primaryKey: 'assignmentCode',
    label: 'Task',
    recordType: 'task',
    initialData: (defaults = {}) => ({
      assignmentCode: `TASK-${Date.now()}`,
      assignmentName: '',
      courseCode: '',
      submissionDate: new Date().toISOString().slice(0, 10),
      submissionHour: '23:59',
      notes: '',
      type: 'task',
      ...defaults,
    }),
  },
};

export const generateInitialFormData = (recordType, defaultValues = {}) => {
  if (formMappings[recordType] && typeof formMappings[recordType].initialData === 'function') {
    const initialData = formMappings[recordType].initialData(defaultValues);
    console.log(`[generateInitialFormData] Type: ${recordType}, Data:`, initialData);
    return initialData;
  }

  console.warn(`[generateInitialFormData] No mapping or initialData function found for recordType: ${recordType}`);
  return { id: `TEMP-${Date.now()}`, ...defaultValues };
};